# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-25 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
