# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-25 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_myuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='user_images'),
        ),
    ]
