# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-25 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20171025_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='image',
        ),
        migrations.AddField(
            model_name='myuser',
            name='picture',
            field=models.ImageField(blank=True, upload_to='user_picture'),
        ),
    ]
