# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-30 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_friend_current_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='users',
            new_name='friends',
        ),
    ]
