# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-30 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20171030_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='friends',
            new_name='users',
        ),
    ]
